service:
  image: mysql:8-debian
  roles:
    - db
  driver:
    name: mysql
    config:
      database: mysql
      password: mysql
  run_as_current_user: false
  post_start:
    # Wait for db
    - 'while ! mysqladmin ping -u "root" -p"{{ driver.config.password }}" --silent; do sleep 1; done'